module memory_coalescing_unit /* #(
    // parameter int ID_W = 1 (used later when changing cache to non-blocking)
)*/ (
    input logic clk,
    input logic reset,
    // input from ALU
    input logic [7:0][31:0] addr,
    input logic [7:0][31:0] src2, // store data
    input logic [7:0] valid,
    input logic is_load,
    input logic is_store,
    input logic sub_warp_valid,
    input logic [1:0] sub_warp_cycle,
    input logic [9:0] reg_bank_addr,

    // interface to data cache
    output logic req_valid,
    input logic req_ready,
    output logic [31:0] req_addr,
    output logic req_write,
    output logic [1023:0] wr_data,
    output logic [31:0] wr_word_en,

    // output to load store unit
    output logic txn_valid,
    output logic txn_is_load,
    output logic txn_last,
    output logic [2:0] txn_warp,
    output logic [4:0] txn_dst,
    output logic [31:0] txn_match_mask,
    output logic [31:0][4:0] txn_word_sel // select requested word from cache line
);
    typedef enum logic [1:0] {
        EMPTY,
        ACCUM,
        READY,
        ISSUING
    } slot_state_t;

    // Per-warp instruction storage
    //    [warp][thread][data]
    logic [7:0][31:0][31:0] slot_addr; // Memory address generated by each thread
    logic [7:0][31:0][31:0] slot_store_data; // Store value from each thread

    //    [warp][thread]
    logic [7:0][31:0] slot_mask; // Active threads for this instruction
    logic [7:0][31:0] slot_claimed; // Threads already included in accepted cache transactions

    // Instruction metadata
    logic [7:0] slot_is_store; // no need for slot_is_load since its simply ~slot_is_store
    logic [7:0][4:0] slot_dst; // destination register

    // Current state of each warp's slot
    slot_state_t slot_state [7:0]; // current state for each warp

    logic [7:0][2:0] ready_fifo;
    logic [3:0] ready_count;

    logic [2:0] incoming_warp;
    logic [4:0] incoming_dst;

    assign incoming_warp = reg_bank_addr[9:7];
    assign incoming_dst  = reg_bank_addr[4:0];

    always_ff @(posedge clk) begin
        if (sub_warp_valid && (is_load || is_store)) begin
            slot_addr[incoming_warp][sub_warp_cycle*8 +: 8] <= addr;
            slot_store_data[incoming_warp][sub_warp_cycle*8 +: 8] <= src2;
            slot_mask[incoming_warp][sub_warp_cycle*8 +: 8] <= valid;
            slot_is_store[incoming_warp] <= is_store;
            slot_dst[incoming_warp] <= incoming_dst;
        end
    end

    logic fifo_push, fifo_pop;
    logic [2:0] issuing_warp;
    logic issue_active;
    logic issue_done;
    logic direct_handoff;

    assign issue_done = req_valid && req_ready && txn_last;

    assign fifo_push = sub_warp_valid && (is_load || is_store) && (&sub_warp_cycle);
    assign fifo_pop = |ready_count && (!issue_active || issue_done);

    assign direct_handoff = (ready_count == 0) && fifo_push && (issue_done || !issue_active);

    always_ff @(posedge clk) begin
        if (reset)
            ready_count <= 4'd0;
        else begin
            case ({fifo_push && !direct_handoff, fifo_pop})
                2'b10 : begin // push only
                    ready_fifo[ready_count] <= incoming_warp;
                    ready_count <= ready_count + 4'd1;
                end

                2'b01 : begin // pop only
                    for (int i = 0; i < 7; ++i) begin
                        ready_fifo[i] <= ready_fifo[i + 1];
                    end
                    ready_count <= ready_count - 4'd1;
                end

                2'b11 : begin // push and pop
                    for (int i = 0; i < 7; ++i)
                        ready_fifo[i] <= ready_fifo[i + 1];
                    
                    ready_fifo[ready_count - 1] <= incoming_warp;
                    // ready_count doesn't change since one left and one entered
                end

                default : ; // do nothing
            endcase
        end
    end

    always_ff @(posedge clk) begin        
        if (reset) begin
            issuing_warp <= 3'b0;
            issue_active <= 1'b0;

            for (int w = 0; w < 8; ++w) begin
                slot_state[w] <= EMPTY;
                slot_claimed[w] <= '0;
            end
        end else begin
            if (sub_warp_valid && (is_load || is_store)) begin
                if (~|sub_warp_cycle)
                    slot_claimed[incoming_warp] <= '0;

                slot_state[incoming_warp] <= (&sub_warp_cycle) ? READY : ACCUM;
            end   

            if (fifo_pop) begin
                issuing_warp <= ready_fifo[0];
                issue_active <= 1'b1;
                slot_state[ready_fifo[0]] <= ISSUING;
            end else if (direct_handoff) begin
                issuing_warp <= incoming_warp;
                issue_active <= 1'b1;
                slot_state[incoming_warp] <= ISSUING;
            end else if (issue_done) begin
                issue_active <= 1'b0;
            end

            if (req_valid && req_ready) begin
                if (!txn_last)
                    slot_claimed[issuing_warp] <= slot_claimed[issuing_warp] | group_mask;
                else
                    slot_state[issuing_warp] <= EMPTY;
            end
        end
    end

    logic [31:0] remaining;

    logic [4:0] selected_thread;
    logic selected_thread_valid;
    
    logic [24:0] selected_line;
    logic [31:0] group_mask;

    always_comb begin
        remaining = slot_mask[issuing_warp] & ~slot_claimed[issuing_warp];
        
        selected_thread = 5'd0;
        selected_thread_valid = |remaining;
        
        for (int t = 31; t >= 0; --t) begin
            if (remaining[t]) begin
                selected_thread = t[4:0];
            end
        end
        
        selected_line = slot_addr[issuing_warp][selected_thread][31:7];

        for (int t = 0; t < 32; ++t)
            group_mask[t] = remaining[t] && (slot_addr[issuing_warp][t][31:7] == selected_line);
        
        req_valid = issue_active && selected_thread_valid;
        req_addr = {selected_line, 7'b0};
        req_write = slot_is_store[issuing_warp];

        wr_data = '0;
        wr_word_en = '0;
        for (int t = 0; t < 32; ++t) begin
            if (group_mask[t]) begin
                wr_data[slot_addr[issuing_warp][t][6:2] * 32 +: 32] = slot_store_data[issuing_warp][t];
                wr_word_en[slot_addr[issuing_warp][t][6:2]] = 1'b1;
            end
        end

        txn_valid = req_valid && req_ready;
        txn_is_load = !slot_is_store[issuing_warp];
        txn_warp = issuing_warp;
        txn_dst = slot_dst[issuing_warp];
        txn_match_mask = group_mask;
        txn_last = selected_thread_valid && (remaining == group_mask);

        for (int t = 0; t < 32; ++t) begin
            txn_word_sel[t] = slot_addr[issuing_warp][t][6:2];
        end
    end

    // Simulation assertions
    `ifndef SYNTHESIS
        // A new memory instruction must not overwrite an occupied slot
        always_ff @(posedge clk) begin
            if (!reset && sub_warp_valid && (is_load || is_store) && ~|sub_warp_cycle) begin
                assert (slot_state[incoming_warp] == EMPTY)
                    else $error("Coalescer: warp %0d started a new memory instruction while slot state = %0d",
                                incoming_warp, slot_state[incoming_warp]);
            end
        end

        // Subwarps 1-3 should belong to an instruction currently being accumulated
        always_ff @(posedge clk) begin
            if (!reset && sub_warp_valid && (is_load || is_store) && |sub_warp_cycle) begin
                assert (slot_state[incoming_warp] == ACCUM)
                    else $error("Coalescer: warp %0d received subwarp %0d while slot state = %0d",
                                incoming_warp, sub_warp_cycle, slot_state[incoming_warp]);
            end
        end

        // Ready FIFO can never contain more than 8 warps
        always_ff @(posedge clk) begin
            if (!reset) begin
                assert (ready_count <= 8)
                    else $error("Coalescer: ready FIFO overflow, ready_count = %0d", ready_count);
            end
        end
    `endif
endmodule
